# Generated by Django 3.0.4 on 2020-04-04 22:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("causes", "0004_auto_20200404_2253"),
    ]

    operations = [
        migrations.CreateModel(
            name="CauseCoordinator",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("country", django_countries.fields.CountryField(max_length=2)),
                (
                    "cause",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="causes.Cause"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Coordinator",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "causes",
                    models.ManyToManyField(
                        related_name="coordinators",
                        through="coordinators.CauseCoordinator",
                        to="causes.Cause",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="coordinators",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="causecoordinator",
            name="coordinator",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="coordinators.Coordinator",
            ),
        ),
    ]
