# Generated by Django 3.0.4 on 2020-03-22 16:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("causes", "0002_auto_20200322_1620"),
        ("therapists", "0002_auto_20200319_0741"),
    ]

    operations = [
        migrations.AddField(
            model_name="therapist",
            name="active",
            field=models.BooleanField(blank=True, default=True),
        ),
        migrations.AlterField(
            model_name="therapist",
            name="causes",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="therapists",
                to="causes.Cause",
            ),
        ),
        migrations.AlterField(
            model_name="therapist",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="therapist",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
