# Generated by Django 3.0.4 on 2020-03-22 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('causes', '0002_auto_20200322_1620'),
        ('therapists', '0003_auto_20200322_1620'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='therapist',
            name='causes',
        ),
        migrations.AddField(
            model_name='therapist',
            name='causes',
            field=models.ManyToManyField(blank=True, null=True, related_name='therapists', to='causes.Cause'),
        ),
    ]
