# Generated by Django 3.0.4 on 2020-03-22 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('therapists', '0004_auto_20200322_1638'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='therapist',
            options={'ordering': ('busy',)},
        ),
        migrations.AddField(
            model_name='therapist',
            name='psychologist',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='therapist',
            name='psychotherapist',
            field=models.BooleanField(blank=True, default=True),
        ),
        migrations.AddField(
            model_name='therapist',
            name='therapist',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
