# Generated by Django 3.0.4 on 2020-03-16 15:58

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cause',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('countries', django_countries.fields.CountryField(max_length=746, multiple=True)),
                ('website', models.URLField()),
            ],
        ),
    ]
