# Generated by Django 3.0.4 on 2020-04-04 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("causes", "0002_auto_20200322_1620"),
    ]

    operations = [
        migrations.AddField(
            model_name="cause", name="slug", field=models.SlugField(default="covid_19"),
        ),
    ]
