# Generated by Django 3.0.4 on 2020-04-04 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("causes", "0003_cause_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cause", name="slug", field=models.SlugField(),
        ),
    ]
